services:
    sharelatex:
        restart: always
        image: code.lcpu.dev/lcpu/sharelatex:latest
        container_name: sharelatex
        depends_on:
            mongo:
                condition: service_healthy
            redis:
                condition: service_started
        ports:
            - 5000:80
        links:
            - mongo
            - redis
        volumes:
            - /opt/volumes/sharelatex/data:/var/lib/overleaf
            - /var/run/docker.sock:/var/run/docker.sock
        environment:
            OVERLEAF_APP_NAME: PKU LaTeX
            OVERLEAF_MONGO_URL: mongodb://mongo/sharelatex
            OVERLEAF_REDIS_HOST: redis
            REDIS_HOST: redis
            ENABLED_LINKED_FILE_TYPES: 'project_file,project_output_file'
            ENABLE_CONVERSIONS: 'true'
            EMAIL_CONFIRMATION_DISABLED: 'true'
            TEXMFVAR: /var/lib/overleaf/tmp/texmf-var
            OVERLEAF_BEHIND_PROXY: 'true'
            OVERLEAF_SECURE_COOKIE: 'true'
            OVERLEAF_SITE_URL: https://latex.pku.edu.cn/
            OVERLEAF_NAV_TITLE: PKU LaTeX
            OVERLEAF_HEADER_IMAGE_URL: https://latex.pku.edu.cn/img/pkutex-white.svg
            OVERLEAF_ADMIN_EMAIL: 'lcpu@pku.edu.cn'
            OVERLEAF_LEFT_FOOTER: '[{"text": "由北京大学学生 Linux 俱乐部构建并维护. 感谢 <a href=\"https://osslab-pku.github.io\">北京大学开源软件数据分析实验室</a>支持"},{"text":"<a href=\"https://github.com/lcpu-club/overleaf\">GitHub repo</a>"} ]'
            OVERLEAF_RIGHT_FOOTER: '[{"text": "v0.2.0-alpha, pre stable release"} ]'
            OVERLEAF_SITE_LANGUAGE: 'zh-CN'
            OVERLEAF_IS_SERVER_PRO: true
            # Sandboxed Compile
            DOCKER_RUNNER: true
            DOCKER_USER: "www-data"
            SANDBOXED_COMPILES_HOST_DIR: '/opt/volumes/sharelatex/data/data/compiles'
            SANDBOXED_COMPILES_CONTAINER_TIMEOUT: 3600000
            TEX_LIVE_DOCKER_IMAGE: "code.lcpu.dev/lcpu/sharelatex-base:2024.1"
            ALL_TEX_LIVE_DOCKER_IMAGES: "code.lcpu.dev/lcpu/sharelatex-base:2024.1,code.lcpu.dev/lcpu/sharelatex-base:2022.1,code.lcpu.dev/lcpu/sharelatex-base:2020.1"
            ALL_TEX_LIVE_DOCKER_IMAGE_NAMES: "TeX Live 2024,TeX Live 2022,TeX Live 2020"

    mongo:
        restart: always
        image: docker.smirrors.lcpu.dev/library/mongo:5
        container_name: mongo
        ports:
            - 127.0.0.1:27017:27017
        volumes:
            - /opt/volumes/sharelatex/mongo:/data/db
        healthcheck:
            test: echo 'db.stats().ok' | mongo localhost:27017/test --quiet
            interval: 10s
            timeout: 10s
            retries: 5

    redis:
        restart: always
        image: docker.smirrors.lcpu.dev/library/redis:6.2
        container_name: redis
        expose:
            - 6379
        volumes:
            - /opt/volumes/sharelatex/redis:/data
